Repository edgarmauricio123/Crud_alumnos_Spring_Vue, pull requests merged in 2025-05, with the labels that each got.

#1 Edgar
  .vscode/settings.json
  alumnos/src/main/java/Equipo/DMME/alumnos/model/AlumnoModel.java
  alumnos/src/main/java/Equipo/DMME/alumnos/repository/AlumnoRepository.java
  alumnos/src/main/resources/application.properties
Labels: Backend

#4 Marlene
  .gitignore
  alumnos/.gitignore
  alumnos/.vscode/settings.json
  alumnos/alumnos/.gitattributes
  alumnos/alumnos/.gitignore
  alumnos/alumnos/.mvn/wrapper/maven-wrapper.properties
  alumnos/alumnos/mvnw
  alumnos/alumnos/mvnw.cmd
  alumnos/alumnos/pom.xml
  alumnos/alumnos/src/main/java/Equipo/DMME/alumnos/AlumnosApplication.java
  alumnos/alumnos/src/main/java/Equipo/DMME/alumnos/controllers/AlumnoController.java
  alumnos/alumnos/src/main/java/Equipo/DMME/alumnos/model/AlumnoModel.java
  alumnos/alumnos/src/main/java/Equipo/DMME/alumnos/repository/AlumnoRepository.java
  alumnos/alumnos/src/main/resources/application.properties
  alumnos/alumnos/src/test/java/Equipo/DMME/alumnos/AlumnosApplicationTests.java
  alumnos/src/main/resources/application.properties
Labels: Backend

#8 Correcion de errores por desbordamiento de tabla y agregacion de esti…
  front_alumnos/index.html
  front_alumnos/src/App.vue
  front_alumnos/src/style.css
Labels: Frontend

#12 Conflicto para hacer un merge de de la rama realease a la rama main
  front_alumnos/index.html
  front_alumnos/src/App.vue
Labels: bug
